title: Ashley Flick
subtitle: My Personal Website
email: aflick@nd.edu
description: Welcome to my website!
baseurl: ""
url: "https://aflick-design.github.io"
cover: "/assets/your-cover-image.jpg"
logo: "/assets/your-logo.png"
