title: Ashley Flick
subtitle: My Personal Website
email: aflick@nd.edu
description: Welcome to my website!
baseurl: ""
url: "https://aflick-design.github.io"
cover: "/assets/header_image.jpg"
logo: "/assets/my-headshot.jpg"
